<?php
return [
    'dashboard' => ['icon' => 'fa-tv', 'title' => 'Dashboard'],
    'interfaces' => ['icon' => 'fa-ethernet', 'title' => 'Interfaces'],
    'services' => ['icon' => 'fa-cogs', 'title' => 'Services'],
    'system_config' => ['icon' => 'fa-server', 'title' => 'System Config'],
    'setup_wizard' => ['icon' => 'fa-wrench', 'title' => 'Setup Wizard'],
    'poweroff' => ['icon' => 'fa-power-off', 'title' => 'Power Off'],
    'reboot' => ['icon' => 'fa-refresh', 'title' => 'Reboot'],
    // 'logs' => ['icon' => 'fa-history', 'title' => 'Logs'],
    // 'data_management' => ['icon' => 'fa-database', 'title' => 'Data Management'],
    // 'devices' => ['icon' => 'fa-laptop', 'title' => 'Devices'],
    // 'dns_entries' => ['icon' => 'fa-list', 'title' => 'DNS Entries'],
    // 'statistics' => ['icon' => 'fa-area-chart', 'title' => 'Statistics'],
    // 'security' => ['icon' => 'fa-shield', 'title' => 'Security'],
    // 'performance' => ['icon' => 'fa-tachometer', 'title' => 'Performance'],
    // 'administrators' => ['icon' => 'fa-address-card', 'title' => 'Administrators'],
    // 'alerts' => ['icon' => 'fa-bell', 'title' => 'Alerts'],
    // 'general_settings' => ['icon' => 'fa-cog', 'title' => 'General Settings'],
    // 'advanced_settings' => ['icon' => 'fa-wrench', 'title' => 'Advanced Settings'],
];
